[16.0][IMP] sale_channel_search_engine: No sale_channel, no mark_to_update
OCA/sale-channel pull request #15
Opened 2024-02-22 11:06 UTC by qgroulard

Avoid update on bindings from products not linked to sale channels

For instance, a binding set 'to_delete' because removed from a sale channel should not be set 'to_recompute' by a to "_se_mark_to_update()".

We encounter this bug when using [shopinvader_search_engine_update](https://github.com/shopinvader/odoo-shopinvader/tree/16.0/shopinvader_search_engine_update), as `_se_mark_to_update()` will be called when `sale_channel_ids` is modified to remove a record from a sale channel. `_synchronize_channel_index()` from `sale_channel_search_engine` would mark the binding as 'to_delete', but then `_se_mark_to_update()` is called and replace 'to_delete' by 'to_recompute'.

2024-06-17 08:00 UTC, qgroulard commented
ping @sebastienbeau @hparfr

2024-10-23 09:06 UTC, qgroulard commented
@sebastienbeau @hparfr :pray:

2024-10-23 11:21 UTC, hparfr approved these changes
sorry of the delay

2025-06-06 20:35 UTC, sebastienbeau requested changes
I don't think it's the right way of doing it.
We can have other case where the binding is "to_delete" and a "_mark_to_update" is trigged.
I think we should fix it in "connector_search_engine" directly

2025-06-06 20:45 UTC, sebastienbeau commented
@qgroulard can you check this fix? https://github.com/OCA/search-engine/pull/212
Take a look to the last commit

2026-07-28 06:34 UTC, rousseldenis commented
@qgroulard What's the status of this ?

2026-07-28 07:56 UTC, qgroulard commented
I close this PR, the issue has been fixed in https://github.com/OCA/search-engine/pull/212

2026-07-28 07:56 UTC, closed without merging