[16.0][ADD] sale_channel_notification
OCA/sale-channel pull request #22
Opened 2024-07-08 08:30 UTC by mathieudelva

2024-10-29 14:50 UTC, Kev-Roche requested changes

2024-10-29 14:50 UTC, Kev-Roche commented on sale_channel_notification/README.rst
> +Simple module that adds the posibility to link an email template to an action.
Please, can you develop a little.

2024-10-29 14:50 UTC, Kev-Roche commented on sale_channel_notification/models/sale_order.py
> +        # désactiver l'envoie de mail natif
English please

2024-10-29 14:50 UTC, Kev-Roche commented on sale_channel_notification/models/stock_picking.py
> +    @api.onchange("carrier_id")
```suggestion
    @api.onchange("carrier_id", "sale_id.sale_channel_id")
```

2024-10-29 14:50 UTC, Kev-Roche commented on sale_channel_notification/tests/test_sale_order.py
> +            {
A single test file / class with the same setup() and all the tests is ok.

2026-08-24 14:38 UTC, sebastienbeau commented
I close it as a the #45 replace it

2026-08-24 14:38 UTC, closed without merging