[16.0] add sale channel product catalog
OCA/sale-channel pull request #9
Opened 2023-06-19 16:21 UTC by hparfr

2023-06-21 11:53 UTC, rousseldenis commented
@hparfr Could you include depending PR's in description and embed them here to easy review and testing following https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29 ?

Thanks

2024-01-29 11:05 UTC, acsonefho requested changes

2024-01-29 11:05 UTC, acsonefho commented on sale_channel_product_catalog/models/sale_channel.py
> +    product_catalog = fields.Many2one("product.catalog")
`product_catalog_id = fields.Many2one("product.catalog")`

2024-01-29 11:05 UTC, acsonefho commented on sale_channel_search_engine_product_catalog/models/product_catalog.py
> +        if "active" in self._fields:
IMO it's not useful. `active` field exist on the `self` (catalog). It's not logic to test if every fields exist.

2024-03-03 12:27 UTC, closed without merging